name: Run Playwright Pytest and Upload HTML Report

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '30 5 * * *'  # Runs at 11:00 AM IST (IST is UTC+5:30)

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          playwright install

      - name: Run Playwright Pytest Tests
        run: |
          pytest

      - name: Install Allure
        run: |
          # Download Allure
          curl -L -o allure.zip "https://github.com/allure-framework/allure2/releases/latest/download/allure-2.20.1.zip"
          
          # Check if download was successful
          if [ ! -f allure.zip ]; then
            echo "Allure download failed!"
            exit 1
          fi
          
          # Unzip
          unzip allure.zip -d allure

          # Check if unzip was successful
          if [ $? -ne 0 ]; then
            echo "Failed to unzip allure.zip"
            exit 1
          fi
          
          # Move to /usr/local/bin
          sudo mv allure/bin/allure /usr/local/bin/allure

          # Clean up
          rm -rf allure allure.zip

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-html-report
          path: allure-report/  # Path to the generated HTML report
