name: Run Playwright Pytest and Upload HTML Report

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '30 5 * * *'  # Runs at 11:00 AM IST (IST is UTC+5:30)

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          playwright install
      
      - name: Install Allure
        run: |
          sudo apt-get install -y openjdk-11-jdk
          wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.31.0.zip
          unzip allure-2.31.0.zip -d /opt/
          sudo ln -s /opt/allure-2.31.0.zip/bin/allure /usr/bin/allure
          echo 'export PATH=$PATH:/opt/allure-2.31.0/bin' >> $GITHUB_ENV

      - name: Run Playwright Pytest Tests
        run: |
          pytest

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-html-report
          path: allure-report/  # Path to the generated HTML report
